### PR TITLE
Patch Rails security issue not fixed in a 3.2.x

### PR DESCRIPTION
**Pull request by edds**

### CODE REVIEW

**Comment by alext** [comment]
Can we wrap this in a conditional that will raise an error if the Rails version is different than expected so that we know when to review/remove the patch.

**Comment by jamiecobbett** [comment]
@alext if we do, @boffbowsh should update the gist: https://gist.githubusercontent.com/boffbowsh/073d4f36f8677304fa9f/raw/c5eebb5b80c5f261917aab94555805ef34db9cc3/cve_2015_3226_fix.rb

**Comment by edds** [comment]
Hows that?

**Comment by alext** [comment]
Looks good.  Possibly worth including `__FILE__` in that error string so people know where to look.

**Comment by alext** [comment]
but that'll be in the backtrace, so ignore me...

**Comment by boffbowsh** [comment]
I'll update the gist, good idea @alext

**Pull request merged**
