### PR TITLE
Create new survey test - decrease frequency that survey shows for 48 hours

### PR DESCRIPTION
**Pull request by fofr**
* Remove old test, add new test, fix pending spec.
* Test will run from May 4 to May 5.

https://trello.com/c/YN1CU7jB/385-gov-uk-survey-test-for-may-small

### CODE REVIEW

**Comment by fofr** [comment]
Looks like Jenkins is having problems.

**Comment by dsingleton** [comment]
> Looks like Jenkins is having problems.

Same issue as we saw the other day, one of the jenkins machines is unavailable and the job is running on a different one that is failing. Being looked at by @alexmuller at the moment.

**Comment by dsingleton** [comment]
Changes look good to me, be happy to merge once the CI issues are resolved.

**Comment by fofr** [comment]
Fixed tests: `surveyFrequency() { }` is fine when not minified, but causes a parse error when minified because it should be `surveyFrequency: function() {}`

**Pull request merged**
