### PR TITLE
Remove dependency on <article> tags

### PR DESCRIPTION
**Pull request by edds**
Currently to introduce a standardised styling on blocks of content you have to wrap that content in an article tag. This removes the dependancy on an article tag and instead lets you wrap the section in an element with the class `content-block`.

There is also some misc tidying up which was revealed when looking for instances of article tags. Check the commits for more details.

### CODE REVIEW

**Comment by fofr** [comment]
I like this a lot :smile:

**Comment by dsingleton** [comment]
:raised_hands: Huge improvement.

**Comment by tombye** [comment]
Brilliant and long overdue :+1:

**Comment by edds** [comment]
This would enabled us to make changes like this: https://github.com/alphagov/frontend/pull/743

**Pull request merged**
