### PR TITLE
Reduce frequency of content pages design surveys

### PR DESCRIPTION
**Pull request by maxgds**
Surveys currently appear too frequently, this PR reduces that.

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Do we also need to reduce the frequency of `GOVUK_content_pages_design_survey_2` or is it just `GOVUK_content_pages_design_survey_1`?

**Comment by maxgds** [comment]
Good spot, it should be both. Will fix.

**Comment by maxgds** [comment]
@vanitabarrett now applied to both surveys

**Comment by vanitabarrett** [comment]
@maxgds Changes all look good to me, not sure what the Jenkins failure means though.

**Pull request merged**
