### PR TITLE
Use GOV.UK Template version 0.20.0

### PR DESCRIPTION
**Pull request by gemmaleigh**
# 0.20.0

- Fix EJS template - [PR #270](https://github.com/alphagov/govuk_template/pull/270)
- Add `theme-color` support to make the page surround in Chrome’s tab
view on Android match the black GOV.UK header - [PR #278](
 https://github.com/alphagov/govuk_template/pull/278)
- Add `text-decoration-skip: ink` to all links on GOV.UK - [PR #281](
https://github.com/alphagov/govuk_template/pull/281)
- Improve contrast of links when focused - [PR #272](https://github.com/alphagov/govuk_template/pull/272)
- Make header text colour black when focused - [PR #274](https://github.com/alphagov/govuk_template/pull/274)

# 0.19.2

- Increase skiplink colour contrast - [PR #263](https://github.com/alphagov/govuk_template/pull/263)
- Fix Scala compile issues for Play template - [PR #261](
https://github.com/alphagov/govuk_template/pull/261)

# 0.19.1

- Have focus outline appear outside of element rather than covering it
in Safari and Chrome - [PR #259](
https://github.com/alphagov/govuk_template/pull/259)

### CODE REVIEW

**Comment by nickcolley** [comment]
Thanks Gemma :)

This requires the following updates https://github.com/alphagov/static/issues/848

**Comment by fofr** [comment]
* The tweak reported here: https://github.com/alphagov/static/issues/848, no longer appears necessary: https://github.com/alphagov/static/issues/848#issuecomment-299437109.
* Chrome doesn't handle the `ink` style links nicely for `y` characters: https://github.com/alphagov/govuk_template/pull/281#issuecomment-299433758 (but letters like `p` and `g` are more readable)

**Comment by nickcolley** [comment]
Closing in favour of #994 https://github.com/alphagov/static/pull/994

**Comment by fofr** [comment]
Have rebased and pushed.

**Comment by nickcolley** [comment]
Thanks @fofr 👍

**Pull request merged**
