### PR TITLE
Change phase banners from pink and orange to blue

### PR DESCRIPTION
**Pull request by fofr**
Bump toolkit to 5.0.2 to pick up latest design change
Change discussed here: https://github.com/alphagov/govuk_frontend_toolkit/pull/353

## Screenshots

screen shot 2016-12-01 at 13 00 25
screen shot 2016-12-01 at 13 08 48

cc @robinwhittleton @edwardhorsford

### CODE REVIEW

**Comment by nickcolley** [comment]
This looks good to me, which teams currently are using these so we can let them review?

**Comment by fofr** [comment]
@nickcolley All the teams?

**Comment by nickcolley** [comment]
:{P Not all teams are using these banners though, might be being too cautious ;)

**Comment by fofr** [comment]
Uses of the component: https://github.com/search?p=2&q=org%3Aalphagov+beta_label&ref=searchresults&type=Code&utf8=%E2%9C%93

**Comment by nickcolley** [comment]
LGTM 👍

**Pull request merged**
