### PR TITLE
Bump GDS API adapters to 20.1.1

### PR DESCRIPTION
**Pull request by elliotcm**
This changes the user agent to include the app
name in API requests.

https://trello.com/c/qkHdtob4/247-bump-gds-api-adapters-everywhere-it-s-used-to-include-user-agent-information

### CODE REVIEW

**Comment by mattbostock** [comment]
Can you please add something to the commit message to explain the change to the tests?

**Comment by elliotcm** [comment]
@mattbostock You mean the change to the rake task?

**Comment by mattbostock** [comment]
Yes, sorry.

**Comment by elliotcm** [comment]
@mattbostock No problem, done.

**Comment by mattbostock** [comment]
Thanks @elliotcm :+1:

**Pull request merged**
