### PR TITLE
Add YouTube embed example to Govspeak Component

### PR DESCRIPTION
**Pull request by dsingleton**
Youtube links in govspeak will be converted into an embedded video
player.

Add an example of this to the fixtures for the govspeak component.

**Screenshot from local copy of `govuk-component-guide`:**

govspeak content with youtube embed gov uk component guide

### CODE REVIEW

**Comment by jamiecobbett** [comment]
At first I thought this was a feature of the Govspeak gem, but its actually a feature of the Javascript in static. Is it worth making that clear somehow?

**Comment by boffbowsh** [comment]
:+1: but what Jamie said

**Comment by fofr** [comment]
Added a commit to clarify that the embedded player comes via a script in static.

**Comment by dsingleton** [comment]
Updated the documentation describing the Govspeak component itself, to clarify your comments @jamiecobbett and @boffbowsh. Does that help?

(@fofr I rolled your commit into mine, sorry)

**Pull request merged**
