### PR TITLE
Replace exception_notification integration with Errbit/Airbrake

### PR DESCRIPTION
**Pull request by benilovj**
Errbit is the current approach in our stack for tracking errors.

Related PRs:

- https://github.gds/gds/puppet/pull/3390
- https://github.gds/gds/deployment/pull/706
- https://github.gds/gds/alphagov-deployment/pull/1053

### CODE REVIEW

**Comment by jamiecobbett** [comment]
Merge when ready :+1:

**Comment by tijmenb** [comment]
:+1: 

You can also remove `action_mailer` now I think: https://github.com/alphagov/static/blob/master/config/application.rb#L4

**Comment by benilovj** [comment]
@tijmenb well spotted, https://github.com/alphagov/static/pull/653

**Pull request merged**
