### PR TITLE
Add scroll tracking to business finance support finder

### PR DESCRIPTION
**Pull request by zilnhoj**

### CODE REVIEW

**Comment by dsingleton** [comment]
The [test failure](https://ci-new.alphagov.co.uk/job/govuk_static_branches/436/console) looks related to @quis' change in https://github.com/alphagov/static/pull/556.

**Comment by dsingleton** [comment]
@zilnhoj @edds is going to see if there's a quick fix for the issue, if not we'll temporally roll it back so other changes can go through.

**Comment by quis** [comment]
@dsingleton @edds @zilnhoj Should be fixed by merging #566

**Comment by dsingleton** [comment]
@zilnhoj you'll need to rebase the fix into your changes for the tests to pass. I can run you through that if you need a hand?

**Pull request merged**
