### PR TITLE
Upgrade jQuery to 1.12.4 (take 2)

### PR DESCRIPTION
**Pull request by fofr**
Same as https://github.com/alphagov/static/pull/869 but with added fix for jquery tabs.

> Performance of the selector engine has improved thanks to a shortcut path that immediately uses precompiled Sizzle selectors when the selector cannot be processed by the native querySelectorAll or matchesSelector methods. This results in a significant speedup in some real-world cases.

Release notes:
https://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/
https://blog.jquery.com/2016/02/22/jquery-1-12-1-and-2-2-1-released/
https://blog.jquery.com/2016/03/17/jquery-1-12-2-and-2-2-2-released/
https://blog.jquery.com/2016/04/05/jquery-1-12-3-and-2-2-3-released/
https://blog.jquery.com/2016/05/20/jquery-1-12-4-and-2-2-4-released/

Similar to previous upgrade jQuery PR:
https://github.com/alphagov/static/pull/628

### CODE REVIEW

**Comment by 36degrees** [comment]
_I've changed the required status checks for this repo. You'll need to rebase this branch against master so that this branch gets a Jenkinsfile can be built against new CI._

**Comment by fofr** [comment]
I'm holding off merging this until we have Smokey tracking JS errors.

**Comment by fofr** [comment]
Smokey JS tests are working now (they alerted us to an error with tabs this morning).
It'd be good to get this upgrade out now.

**Comment by fofr** [comment]
I'd dearly love for someone to review this. Is :cake: required?

**Pull request merged**
