### PR TITLE
Remove robots.txt

### PR DESCRIPTION
**Pull request by alexmuller**
This endpoint is now controlled from Puppet.

https://github.com/alphagov/govuk-puppet/commit/8edb77340e01621ad0bdca3ec4369beef23bb56d

### CODE REVIEW

**Comment by alexmuller** [comment]
Test failures look like they might be related to the satisfaction survey.

**Comment by fofr** [comment]
@alexmuller Should be fixed if you rebase.

**Comment by benlovell** [comment]
@alexmuller, @fofr I just rebased this.

**Comment by alexmuller** [comment]
Thanks for fixing!

**Pull request merged**
