### PR TITLE
Add a JS toggle module

### PR DESCRIPTION
**Pull request by dsingleton**
Most of the work done by @fofr. I cherry-picked it off his branch and made a slight tweak in the second commit (which @fofr was happy with).

This is the first use of [JS Modules](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/javascript.md#modules) at the `static` level of GOV.UK, though the [`start`](https://github.com/alphagov/static/pull/738) code was added to support it's use at an application level.

This particular module is for toggling visibility of content and is being added to [support the accessibility toggle on attachments](https://trello.com/c/HLb48j22/280-govspeak-implementing-the-ui-of-attachments-medium), which i'll be adding the `govspeak` component in a follow up PR.

Example usage of the general pattern:
```
<div data-module="toggle">
    <a href="#" class="my-toggle" data-expanded="false" data-controls="target">Toggle</a>
    <div id="target">Target</div>
</div>
```

_Includes a [bump to `govuk_template`](https://github.com/alphagov/static/commit/942118322958115b0c3e7dbfe3d564a33f8531bf)_

**Mergable when:**

- [x] https://github.com/alphagov/govuk_template/pull/203 is merged
- [x] A new version of govuk_template release
- [x] The gem version of govuk_template is updated on this branch

### CODE REVIEW

**Comment by fofr** [comment]
We might need to use a `js-` class for hiding and showing for the non-js case.

I'm happy with 6237ab0, leaving for someone else to review the rest though.

Perhaps @robinwhittleton or @tombye?

**Comment by dsingleton** [comment]
PR to add a `.js-hidden` hook to [govuk_template](https://github.com/alphagov/govuk_template/pull/203) - and i've pre-emptively updated this PR to use it.

Assuming @fofr is happy this can be merged once https://github.com/alphagov/govuk_template/pull/203 is merged, and released, and this PR is updated to use the latest version of `govuk_template`.

**Comment by fofr** [comment]
`.js-hidden` already exists in Whitehall where this will be used first, so it _could_ be merged sooner if the other PR gets blocked.

**Comment by dsingleton** [comment]
`.js-hidden` now comes from a bumped version of `govuk_template`.

**Pull request merged**
