### PR TITLE
Remove 'require' logic from Gemfile

### PR DESCRIPTION
**Pull request by whoojemaflip**
Move the decision point for the `require` out of the Gemfile and into application.rb

### CODE REVIEW

**Comment by nickcolley** [comment]
Nice! We should probably add this to https://github.com/alphagov/govuk_publishing_components#install-gem and also update government-frontend https://github.com/alphagov/government-frontend/blob/master/Gemfile#L11

**Comment by nickcolley** [comment]
Could you add a comment in the gemfile to explain what we're doing here, so people are not confused at why it's false but still displaying in development/heroku

**Comment by whoojemaflip** [comment]
@nickcolley Isn't that what `requires: false` in a Gemfile signifies? That a gem will be required by hand rather than by magic / bundler.

**Comment by nickcolley** [comment]
@whoojemaflip as someone who doesn't frequent gemfiles that's not something I'd know off the top of my head

**Comment by fofr** [comment]
Seems to be working as expected:
http://govuk-static-pr-1137.herokuapp.com/component-guide/

**Comment by nickcolley** [comment]
I'm going to update the gem and government-frontend with this in mind.

**Pull request merged**
