### PR TITLE
Bump govuk_frontend_toolkit to 4.1.0

### PR DESCRIPTION
**Pull request by tijmenb**
This adds support for setting the page variable in Analytics.

https://github.com/alphagov/govuk_frontend_toolkit/pull/203

### CODE REVIEW

**Comment by dsingleton** [comment]
Is there a particular reason for switching to a the [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic-version-constraint)? I think we've only used exact version in the past.

(i'm not sure it makes a huge amount of difference, and we [recommend](https://github.com/alphagov/styleguides/blob/master/ruby.md#gemfile) pessimism for trustworthy gems)

**Comment by tijmenb** [comment]
Nope, no particular reason to do that now. Suppose I thought it couldn't hurt to make the change now to make future updates easier.

**Comment by dsingleton** [comment]
I don't have a strong opinion, just curious. We should be able to trust ourselves to semver properly here, so :shipit:

**Comment by alext** [comment]
> We should be able to trust ourselves to semver properly here

That's also what the Gem styleguide says to do these days - https://github.com/alphagov/styleguides/blob/master/ruby.md#gemfile

**Pull request merged**
