### PR TITLE
Fixed some inconsistencies in the core.js script.

### PR DESCRIPTION
**Pull request by 1DC**
I simply fixed some inconsistencies in the core.js script.

### CODE REVIEW

**Comment by cbaines** [comment]
Thanks for this @1DC . I've triggered the CI process to run, so hopefully that will pass.

Would you consider tweaking the commit message slightly? Putting something like what you have put in the Pull Request description in the commit message, e.g. "Fix stylistic inconsistencies in core.js script" would be much more useful than  "Consistency".

**Comment by 1DC** [comment]
@cbaines will do when I get home, can't do that through GitHub's UI.

**Comment by nickcolley** [comment]
Hi :)

Thanks for this, I think we should merge this, we're moving towards linting using http://standardjs.com/ but that's a big ask for you to update this to use that right now so thank you for getting us closer!

**Comment by nickcolley** [comment]
I've updated the commit message for you @1DC over at https://github.com/alphagov/static/pull/997

**Comment by 1DC** [comment]
Woops! Forgot about this. Thanks @nickcolley

**Pull request merged**
