### PR TITLE
Add title attribute to button component

### PR DESCRIPTION
**Pull request by steventux**
Title is a default HTML attribute and we do make use of this attribute in completed transactions.

### CODE REVIEW

**Comment by selfthinker** [comment]
Under which circumstances do we use titles on buttons or links? I would generally discourage from using it because it is not accessible to many people. Most users wouldn't know how to access it and on mobile devices it's completely inaccessible.
What's the user need?

**Comment by steventux** [comment]
@selfthinker https://github.com/alphagov/frontend/blob/master/app/views/completed_transaction/show.html.erb#L19 uses the title attribute on a button (link).
We'd like to use the button component in frontend formats, this PR provides support for the use of this (global) attribute.

**Comment by selfthinker** [comment]
I tried to find what the reason is for that particular use of the title attribute within the git history, but it was there from the beginning. I assume it was added to let the link make sense out of context for screen readers. That would be fine. But it could be easily misused.

**Comment by fofr** [comment]
@steventux @selfthinker Could we include an accessibility acceptance criteria about appropriate use of the title param?

**Pull request merged**
