### PR TITLE
Link some more domains

### PR DESCRIPTION
**Pull request by andysellick**
Adding some more domains to the cross linker.

### CODE REVIEW

**Comment by andysellick** [comment]
Thanks Ben. Unfortunately there's not really a card for this, it's an ongoing thing. Maybe I could create a card, I'll have a think.

**Comment by benthorner** [comment]
@andysellick sure - I don't think we need a card necessarily. Ideally, we should write something to help a future dev figure out where these came from i.e. why these domains in particular?

**Comment by andysellick** [comment]
I've got some documentation for this whole process in progress, just not quite sure where to put it yet.

**Comment by andysellick** [comment]
@benthorner https://github.com/alphagov/static/pull/1871

**Pull request merged**
